AllCops:
  NewCops: enable
  DisabledByDefault: false
  DisplayCopNames: true
  TargetRubyVersion: 3.0.0
  Exclude:
    - bin/*
    - tmp/**/*
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Lint/UselessAssignment:
  Enabled: true
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: true
  Max: 35
Lint/UriEscapeUnescape:
  Enabled: false
